export const APT_CODE_OPTIONS = [
  "AHTT - CRU - RB",
  "AHTT - TGĐ",
  "AHTT - CRU - SME, VIP",
  "AHTT - GĐK - RB",
  "AHTT - GĐK - SME, VIP",
  "TBH - GĐK - RB",
  "TBH - GĐK - SME, VIP",
  "TBH - TGĐ",
  "VIP/SME - TGĐ",
  "Mass - TGĐ",
  "Check CRU",
  "AHTT - TGĐ - SME, VIP",
  "VIP/SME - GĐK",
  "Mass - GĐK",
  "VB - CRU – RB",
  "VB - CRU - SME, VIP",
  "VB - GĐK – RB",
  "VB - GĐK - SME, VIP",
  "VB - TGĐ – RB",
  "VB - TGĐ - SME, VIP",
  "Hoàn tiền - GĐK – RB",
  "Hoàn tiền - GĐK - SME, VIP",
  "Hoàn tiền - PGĐK – RB",
  "Hoàn tiền - PGĐK - SME, VIP",
  "Hoàn tiền - TGĐ – RB",
  "Hoàn tiền - TGĐ - SME, VIP",
  "Hoàn tiền – PTSP",
  "Hoàn tiền – AF",
  "Hoàn tiền - SME",
  "Sale_Support",
  "CRU_Support",
  "Đối tác - CRU -RB",
  "Đối tác - CRU - SME, VIP",
  "Đối tác - GĐK - RB",
  "Đối tác - GĐK - SME, VIP",
  "Đối tác - TGĐ - SME, VIP",
  "Đối tác - TGĐ - RB",
  "Trưởng ca",
  "Xử lý case gấp",
  "Miss trong giờ",
  "Miss ngoài giờ",
  "Miss quá hạn"
];
