export const UNIT_OPTIONS = [
  "Priority Vĩnh Phúc",
  "Priority Vĩnh Long",
  "Priority Văn Thánh",
  "Priority Văn Quán",
  "Priority Văn Phú",
  "Priority Uông Bí",
  "Priority Từ Sơn",
  "Priority Tô Hiến Thành",
  "Priority Tây Ninh",
  "Priority Tây Hà Nội",
  "Priority Tân Phú",
  "Priority Tân Bình",
  "Priority Trần Thái Tông",
  "Priority Trần Phú",
  "Priority Trần Nguyên Hãn",
  "Priority Trần Lãm",
  "Priority Trần Duy Hưng",
  "Priority Trường Thi",
  "Priority Tràng An",
  "Priority Trung Sơn",
  "Priority Trung Kính",
  "Priority Trung Hòa NC",
  "Priority Trung Chánh",
  "Priority Tiền Giang",
  "Priority Tiên Cát",
  "Priority Thủy Nguyên",
  "Priority Thủ Đức",
  "Priority Thủ Đô",
  "Priority Thụy Khuê",
  "Priority Thạnh Mỹ Lợi",
  "Priority Thường Tín",
  "Priority Thăng Long",
  "Priority Thái Nguyên",
  "Priority Thái Hà",
  "Priority Thái Bình",
  "Priority Thành Đô",
  "Priority Thành Sen",
  "Priority Thành Nam",
  "Priority Thành Công",
  "Priority Thanh Xuân",
  "Priority Thanh Hóa",
  "Priority Sở giao dịch",
  "Priority Sầm Sơn",
  "Priority Sơn Trà",
  "Priority Sông Đà",
  "Priority Sông Lam",
  "Priority Sài Gòn",
  "Priority Quận 3",
  "Priority Quận 2",
  "Priority Quận 10",
  "Priority Quảng Trị",
  "Priority Quảng Ninh",
  "Priority Quảng Nam",
  "Priority Quảng Bình",
  "Priority Quang Trung",
  "Priority Phạm Văn Đồng",
  "Priority Phạm Văn Hai",
  "Priority Phạm Hùng",
  "Priority Phước Tiến",
  "Priority Phương Mai",
  "Priority Phúc Yên",
  "Priority Phú Xuân",
  "Priority Phú Thọ",
  "Priority Phú Quốc",
  "Priority Phú Mỹ Hưng",
  "Priority Phú Lâm",
  "Priority Phú Hội",
  "Priority Phan Huy Ích",
  "Priority Nơ Trang Long",
  "Priority Núi Thành",
  "Priority Ninh Kiều",
  "Priority Nhà Bè",
  "Priority Nha Trang",
  "Priority Ngô Quyền",
  "Priority Ngô Gia Tự",
  "Priority Nguyễn Văn Cừ",
  "Priority Nguyễn Trãi",
  "Priority Nguyễn Tri Phương",
  "Priority Nguyễn Thái Học",
  "Priority Nguyễn Thiện Thuật",
  "Priority Nguyễn Lương Bằng",
  "Priority Nguyễn Hữu Huân",
  "Priority Nguyễn Du",
  "Priority Nghệ An",
  "Priority Nam Định",
  "Priority Nam Từ Liêm",
  "Priority Nam Thăng Long",
  "Priority Nam Sài Gòn",
  "Priority Nam Hà Nội",
  "Priority Mỹ Đình",
  "Priority Móng Cái",
  "Priority Mai Thúc Loan",
  "Priority Lạng Sơn",
  "Priority Lạch Tray",
  "Priority Lạc Trung",
  "Priority Lạc Quần",
  "Priority Lý Tự Trọng",
  "Priority Lý Thường Kiệt",
  "Priority Lê Đức Thọ",
  "Thu hồi nợ dự án",
  "Thu hồi nợ sớm",
  "Thu hồi nợ - đối tác thuê ngoài",
  "VPBS - Công ty chứng khoán VPB",
  "VN POST",
  "TTThẻ Phòng phát triển hạ tầng thẻ",
  "TTThẻ Phòng phát hành thẻ",
  "TTThẻ - Phòng thanh toán đối soát",
  "TTThẻ - Phòng Quản lý Rủi ro thẻ",
  "TT Micro Đông HN",
  "TT Micro Tây HN",
  "TT Micro Trung Sơn",
  "TT Micro Quận 9",
  "TT Micro Quận 11",
  "TT Micro Mỹ Đình",
  "TT Micro Hà Thành",
  "TT Micro Gò Vấp",
  "SME Đồng Tháp",
  "SME Đồng Nai",
  "SME Đông Đô",
  "SME Đà Nẵng",
  "SME Vũng Tàu",
  "SME Vĩnh Phúc",
  "SME Văn Quán",
  "SME Tân Phú",
  "SME Trung Hòa NC",
  "SME Tiền Giang",
  "SME Thủ Đức",
  "SME Thăng Long",
  "SME Thái Nguyên",
  "SME Thái Bình",
  "SME Thành Đô",
  "SME Thanh Hóa",
  "SME Sài Gòn",
  "SME Quảng Trị",
  "SME Quảng Ninh",
  "SME Quảng Bình",
  "SME Quang Trung",
  "SME Phú Thọ",
  "SME Phú Mỹ Hưng",
  "SME Phú Lâm",
  "SME Ninh Bình",
  "SME Nha Trang",
  "SME Nghệ An",
  "SME Nam Định",
  "SME Láng Hạ",
  "SME Long An",
  "SME Kỳ Hòa",
  "SME Kiên Giang",
  "SME Kinh Đô",
  "SME Hồ Chí Minh",
  "SME Hải Phòng",
  "SME Hải Dương",
  "SME Hưng Yên",
  "SME Hòa Bình",
  "SME Hà Tĩnh",
  "SME Hà Nội",
  "SME Hà Nam",
  "SME Huế",
  "SME Gia Định",
  "SME Gia Lai",
  "SME Dak Lak",
  "SME Cộng Hòa",
  "SME Cầu Giấy",
  "SME Cần Thơ",
  "SME Cà Mau",
  "SME Chương Dương",
  "SME Bến Thành",
  "SME Bắc Ninh",
  "SME Bắc Giang",
  "SME Bùi Hữu Nghĩa",
  "SME Bình Định",
  "SME Bình Thuận",
  "SME Bình Dương",
  "SME An Giang",
  "RB Đội Cấn",
  "RB Đội Cung",
  "RB Đồng Xuân",
  "RB Đồng Tâm",
  "RB Đồng Tháp",
  "RB Đồng Nai",
  "RB Đồng Hới",
  "RB Đống Đa",
  "RB Định Công",
  "RB Đăk Lăk",
  "RB Đông Đô",
  "RB Đông Sài Gòn",
  "RB Đông Hà Nội",
  "RB Đông Hà",
  "RB Đông Ba",
  "RB Đông Anh",
  "RB Đò Quan",
  "RB Đà Nẵng",
  "RB Đà Lạt",
  "RB Điện Biên Phủ",
  "RB Âu Cơ",
  "RB Sông Lam",
  "RB Lam Sơn",
  "Thu hồi nợ QC team",
  "Thu hồi nợ pháp lý",
  "RB Kỳ Hòa",
  "RB Kỳ Bá",
  "RB Kiến An",
  "RB Kiên Giang",
  "RB Kinh Đô",
  "RB Kim Liên",
  "RB Khâm Thiên",
  "RB Khánh Hội",
  "RB Hồng Lĩnh",
  "RB Hồ Chí Minh",
  "RB Hố Nai",
  "RB Hải Phòng",
  "RB Hải Dương",
  "RB Hải An",
  "RB Hưng Yên",
  "RB Hòa Hưng",
  "RB Hòa Bình",
  "RB Hào Nam",
  "RB Hàng Xanh",
  "RB Hàm Nghi",
  "RB Hà Đông",
  "RB Hà Tĩnh",
  "RB Hà Tây",
  "RB Hà Thành",
  "RB Hà Nội",
  "RB Hà Nam",
  "RB Huế",
  "RB Hoàng Quốc Việt",
  "RB Hoàng Hoa Thám",
  "RB Hoàn Kiếm",
  "RB Hiệp Hòa",
  "RB Hai Bà Trưng",
  "RB Gò Vấp",
  "RB Giảng Võ",
  "RB Gia Định",
  "RB Gia Lai",
  "RB Gang Thép",
  "RB Cửa Bắc",
  "RB Cộng Hòa",
  "RB Cẩm Phả",
  "RB Cầu Giấy",
  "RB Cần Thơ",
  "RB Cát Linh",
  "RB Cà Mau",
  "RB Chợ Vinh",
  "RB Chợ Lớn",
  "RB Chương Dương",
  "RB Châu Đốc",
  "RB Chánh Hưng",
  "RB Bố Trạch",
  "RB Bỉm Sơn",
  "RB Bến Thủy",
  "RB Bến Thành",
  "RB Bến Ngự",
  "RB Bến Lức",
  "RB Bắc Ninh",
  "RB Bắc Giang",
  "RB Bạch Đằng",
  "RB Bùi Hữu Nghĩa",
  "RB Bình Định",
  "RB Bình Thạnh",
  "RB Bình Thuận",
  "RB Bình Phước",
  "RB Bình Phú",
  "RB Bình Dương",
  "RB Bàu Cát",
  "RB Bà Chiểu",
  "RB Ba Đồn",
  "RB Ba Đình",
  "RB An Sương",
  "RB An Giang",
  "QDE Đội nhập liệu nhanh của KTT MT",
  "QDE Đội nhập liệu nhanh của KTT MN",
  "QDE Đội nhập liệu nhanh của KTT MB",
  "PriorityTrần hưng Đạo",
  "Priority Đội Cấn",
  "Priority Đội Cung",
  "Priority Đồng Xuân",
  "Priority Đồng Tâm",
  "Priority Đồng Tháp",
  "Priority Đồng Nai",
  "Priority Đồng Hới",
  "Priority Đống Đa",
  "Priority Định Công",
  "Priority Đông Đô",
  "Priority Đông Sài Gòn",
  "Priority Đông Hà Nội",
  "Priority Đông Hà",
  "Priority Đông Ba",
  "Priority Đông Anh",
  "Priority Đò Quan",
  "Priority Đà Nẵng",
  "Priority Đà Lạt",
  "Priority Điện Biên Phủ",
  "Priority Ý Yên",
  "Priority Âu Cơ",
  "Priority Yên Hòa",
  "Priority Vỹ Dạ",
  "Priority Vũng Tàu",
  "Priority Vũ Trọng Phụng",
  "Priority Vĩnh Yên",
  "Priority Lê Văn Việt",
  "Priority Lê Văn Sỹ",
  "Priority Lê Văn Lương",
  "Priority Lê Trọng Tấn",
  "Priority Lê Thanh Nghị",
  "Priority Lê Lợi",
  "Priority Lê Hồng Phong",
  "Priority Lê Chân",
  "Priority Láng Hạ",
  "Priority Lái Thiêu",
  "Priority Lào Cai",
  "Priority Long Thành",
  "Priority Long Biên",
  "Priority Long An",
  "Priority Liễu Giai",
  "Priority Linh Đàm",
  "Priority Lam Sơn",
  "Priority Lagi",
  "Priority Kỳ Hòa",
  "Priority Kỳ Bá",
  "Priority Kiến An",
  "Priority Kiên Giang",
  "Priority Kinh Đô",
  "Priority Kim Liên",
  "Priority Khâm Thiên",
  "Priority Khánh Hội",
  "Priority Hồng Lĩnh",
  "Priority Hồ Chí Minh",
  "Priority Hố Nai",
  "Priority Hải Phòng",
  "Priority Hải Dương",
  "Priority Hải An",
  "Priority Hưng Yên",
  "Priority Hưng Vượng",
  "Priority Hóc Môn",
  "Priority Hòa Hưng",
  "Priority Hòa Bình",
  "Priority Hào Nam",
  "Priority Hàng Xanh",
  "Priority Hàm Nghi",
  "Priority Hà Đông",
  "Priority Hà Tĩnh",
  "Priority Hà Tây",
  "Priority Hà Thành",
  "Priority Hà Nội",
  "Priority Hà Nam",
  "Priority Huế",
  "Priority Hoàng Quốc Việt",
  "Priority Hoàng Hoa Thám",
  "Priority Hoàn Kiếm",
  "Priority Hiệp Hòa",
  "Priority Hai Bà Trưng",
  "Priority Gò Vấp",
  "Priority Giảng Võ",
  "Priority Gia Định",
  "Priority Gia Lai",
  "Priority Gang Thép",
  "Priority Dĩ An",
  "Priority Dak Lak",
  "Priority Cửa Bắc",
  "Priority Cộng Hòa",
  "Priority Cẩm Phả",
  "Priority Cầu Giấy",
  "Priority Cần Thơ",
  "Priority Cát Linh",
  "Priority Cà Mau",
  "Priority Chợ Vinh",
  "Priority Chợ Lớn",
  "Priority Chương Dương",
  "Priority Châu Đốc",
  "Priority Chánh Hưng",
  "Priority Bố Trạch",
  "Priority Bỉm Sơn",
  "Priority Bến Thủy",
  "Priority Bến Ngự",
  "Priority Bến Lức",
  "Priority Bắc Ninh",
  "Priority Bắc Hà Nội",
  "Priority Bắc Giang",
  "Priority Bạch Đằng",
  "Priority Bùi Hữu Nghĩa",
  "Priority Bình Định",
  "Priority Bình Thạnh",
  "Priority Bình Thuận",
  "Priority Bình Phước",
  "Priority Bình Phú",
  "Priority Bình Dương",
  "Priority Bình Chánh",
  "Priority Bàu Cát",
  "Priority Bà Chiểu",
  "Priority Ba Đồn",
  "Priority Ba Đình",
  "Priority An Sương",
  "Priority An Giang",
  "Phòng Đổi mới CN & Hỗ trợ Khối Vận hành",
  "Phòng Định chế Tài chính phi ngân hàng và dự án ủy thác",
  "Phòng Định Chế Tài Chính Ngân hàng",
  "Phòng xử lý Tín dụng KHCN phía Nam",
  "Phòng xử lý Tín dụng KHCN phía Bắc",
  "Phòng xử lý Tín dụng KH SME phía Nam",
  "Phòng xử lý Tín dụng KH SME phía Bắc",
  "Phòng xử lý Tín dụng KH Doanh nghiệp lớn phía Nam",
  "Phòng Western Union",
  "Phòng Tái thẩm định Khách hàng lớn và Định chế tài chính",
  "Phòng Tái thẩm định KHCN và SMEs phía Nam",
  "Phòng Tái thẩm định KHCN và SME HO",
  "Phòng Tái thẩm định CIB & CMB phía Nam",
  "Phòng Tài trợ Thương mại",
  "Phòng tiếp thị Kênh điện tử",
  "Phòng Thẻ Doanh Nghiệp và giải pháp thanh toán",
  "Phòng thu hồi nợ SME",
  "Phòng thu hồi nợ KHCN",
  "Phòng Thanh toán - BP THANH TOAN TN",
  "Phòng Thanh toán - BP THANH TOAN QT",
  "Phòng Thanh toán - BP QUAN LY DONG TIEN VA THU HO",
  "Phòng Thanh toán",
  "Phòng Quản lý và cải tiến quy trình và BGĐ trung tâm",
  "Phòng Quản lý Phân khúc Khách hàng ưu tiên",
  "Phòng Quản lý Phân khúc Khách hàng Mass Affluent",
  "Phòng Quản lý mạng lưới khu vực phía Nam",
  "Phòng Quản lý mạng lưới khu vực phía Bắc",
  "Phòng Quản lý Dự Án",
  "Phòng Quản lý bán",
  "Phòng Phát triển Tài trợ thương mại",
  "QLDT và bảo hiểm AIA",
  "Phòng Phát Triển Sản Phẩm-Tín dụng tín chấp",
  "Phòng Phát triển sản phẩm Trade&Cash",
  "Phòng phát triển sản phẩm thẻ TD và cho vay không TSĐB",
  "Phòng Phát triển sản phẩm Thẻ & Pos SME",
  "Phòng Phát triển sản phẩm SME",
  "Phòng phát triển sản phẩm cho vay thế chấp BĐS",
  "Phòng phát triển sản phẩm - Cho vay có TSĐB",
  "Phòng phát triển kinh doanh MB",
  "Phòng phát triển hợp tác",
  "Phòng phát triển Hệ sinh thái - PDC",
  "Phòng Nâng cao Chất lượng dịch vụ",
  "Phòng Nghiệp vụ TT Tài chính",
  "Phòng Nghiệp Vụ Kho Quỹ - BP DIEU HOA VON",
  "Phòng Nghiệp Vụ Kho Quỹ - BP AN TOAN KHO QUY",
  "Phòng MKT và CSKH SME",
  "Phòng hợp tác bảo hiểm",
  "Phòng Huy động vốn & Kiều hối: Phụ trách sản phẩm tiền gửi & chuyển tiền quốc tế",
  "Phòng Dịch vụ Tài khoản cá nhân",
  "Phòng Dịch vụ Số Hóa",
  "Phòng chương trình tiếp thị sản phẩm KHCN",
  "Phòng Chiến lược thu hồi nợ và BGĐ TT Quản lý và thu hồi nợ",
  "Phòng bán hàng tại POS",
  "Phòng  Quản lý và Tối ưu hóa kinh doanh",
  "Pháp chế - Rủi ro - Phòng xử lý vi phạm",
  "khiếu nại",
  "tố cáo",
  "gian lân",
  "Pháp chế - Rủi ro - Phòng kiểm tra tuân thủ",
  "Pháp chế - Rủi ro - Phòng Kiểm soát tuân thủ tại miền nam",
  "Pháp chế - Rủi ro - Phòng chống rửa tiền",
  "Pháp chế - Rủi ro - Phòng chống gian lận và điều tra",
  "P. Chiến lược CNTT & Kiến trúc TT",
  "Mảng Đảm bảo chất lượng Microservice",
  "Mảng Vận hành",
  "Nền tảng Microservice",
  "Mảng Vân hành ứng dụng tương tác",
  "Mảng VH cơ sở dữ liệu (DBA Services)",
  "Mảng VH Cloud/ Nền tảng/ Máy chủ/ TT DL",
  "Mảng Thiết kế trải nghiệm Ứng dụng",
  "Mảng Quản lý dịch vụ ứng dụng Thẻ",
  "Mảng Quản lý dịch vụ ứng dụng NH lõi",
  "Mảng Quản lý Dịch vụ Ứng dụng Nguồn vốn",
  "Mảng QLHT Ngân hàng giao dịch",
  "Mảng PT và Quản trị Dữ liệu Non-bank",
  "Mảng Phát triển và Vận hành số hóa",
  "Mảng Phát triển giải pháp Microservice",
  "Mảng Phát triển & VH NH trực tuyến",
  "Mảng Phát triển & Số hóa Sản phẩm",
  "Mảng Kiểm soát chất lượng tự động",
  "Mảng Cung cấp dịch vụ SP rủi ro",
  "Mảng Cung cấp dịch vụ Microservice",
  "Mảng Cung cấp Dịch vụ CNTT Khối DN",
  "Mảng Cung cấp DVSP Hoạch định NLDN",
  "Mảng CC DVSP Phân tích",
  "Dữ liệu & BC",
  "Mảng CC DVCN cho các Khối hỗ trợ",
  "Marketing PR - Phòng Truyền thông",
  "Marketing PR - Phòng thương hiệu",
  "Khối Rủi ro - Phòng Giám sát rủi ro",
  "Khối Household",
  "KHCN - Vùng 9",
  "KHCN - Vùng 8",
  "KHCN - Vùng 7",
  "KHCN - Vùng 6",
  "KHCN - Vùng 5",
  "KHCN - Vùng 4",
  "KHCN - Vùng 3",
  "KHCN - Vùng 2",
  "KHCN - Vùng 10",
  "KHCN - Vùng 1",
  "Hành chính - Văn phòng HO phía Nam",
  "Hành chính - Phòng quản lý Tài sản",
  "Hành chính - Phòng Mua Sắm Tập Trung",
  "Hành chính - Phòng Hành chính và Ban Giám đốc TT dịch vụ tổ chức",
  "Hành chính - Phòng An Ninh",
  "Hub loan Đà Nẵng",
  "Hub loan Văn Quán",
  "Hub loan Trung Hòa NC",
  "Hub loan Thụy Khuê",
  "Hub loan Thăng Long",
  "Hub loan Sài Gòn",
  "Hub loan Quang Trung",
  "Hub loan Phú Mỹ Hưng",
  "Hub loan Ngô Quyền",
  "Hub loan Nam Định",
  "Hub loan Lý Thường Kiệt",
  "Hub loan Lê Văn Việt",
  "Hub loan Kim Liên",
  "hUB LOAN",
  "Hub loan Giảng Võ",
  "Hub loan Gia Định",
  "Hub loan Chợ Lớn",
  "Hub loan Chương Dương",
  "FC Thu nhắc nợ",
  "FC DV&Chăm sóc KH",
  "FC Cán bộ bán hàng",
  "Dự án LinkID",
  "Dự án Dịch chuyển Trung tâm Dữ liệu",
  "DVKH Đội Cấn",
  "DVKH Đội Cung",
  "DVKH Đồng Xuân",
  "DVKH Đồng Tâm",
  "DVKH Đồng Tháp",
  "DVKH Đồng Nai",
  "DVKH Đồng Hới",
  "DVKH Đống Đa",
  "DVKH Định Công",
  "DVKH Đăk Lăk",
  "DVKH Đông Đô",
  "DVKH Đông Sài Gòn",
  "DVKH Đông Hà Nội",
  "DVKH Đông Hà",
  "DVKH Đông Ba",
  "DVKH Đông Anh",
  "DVKH Đò Quan",
  "DVKH Đà Nẵng",
  "DVKH Đà Lạt",
  "DVKH Điện Biên Phủ",
  "DVKH Ý Yên",
  "DVKH Âu Cơ",
  "DVKH Yên Phong",
  "DVKH Yên Hòa",
  "DVKH Vỹ Dạ",
  "DVKH Vũng Tàu",
  "DVKH Vũ Trọng Phụng",
  "DVKH Vĩnh Yên",
  "DVKH Vĩnh Phúc",
  "DVKH Vĩnh Long",
  "DVKH Văn Thánh",
  "DVKH Văn Quán",
  "DVKH Văn Phú",
  "DVKH Uông Bí",
  "DVKH Từ Sơn",
  "DVKH Tô Hiến Thành",
  "DVKH Tây Ninh",
  "DVKH Tây Hồ",
  "DVKH Tây Hà Nội",
  "DVKH Tân Phú",
  "DVKH Tân Bình",
  "DVKH Trần Thái Tông",
  "DVKH Trần Phú",
  "DVKH Trần Nguyên Hãn",
  "DVKH Trần Lãm",
  "DVKH Trần hưng Đạo",
  "DVKH Trần Duy Hưng",
  "DVKH Trường Thi",
  "DVKH Tràng An",
  "DVKH Trung Sơn",
  "DVKH Trung Kính",
  "DVKH Trung Hòa Nhân Chính",
  "DVKH Trung Chánh",
  "DVKH Tiền Giang",
  "DVKH Tiên Cát",
  "DVKH Thủy Nguyên",
  "DVKH Thủ Đức",
  "DVKH Thủ Đô",
  "DVKH Thụy Khuê",
  "DVKH Thạnh Mỹ Lợi",
  "DVKH Thường Tín",
  "DVKH Thăng Long",
  "DVKH Thái Nguyên",
  "DVKH Thái Hà",
  "DVKH Thái Bình",
  "DVKH Thành Sen",
  "DVKH Thành Nam",
  "DVKH Thành Công",
  "DVKH Thanh Xuân",
  "DVKH Thanh Hóa",
  "DVKH Sở giao dịch",
  "DVKH Sầm Sơn",
  "DVKH Sơn Trà",
  "DVKH Sông Đà",
  "DVKH Sông Lam",
  "DVKH Sài Gòn",
  "DVKH Quận 3",
  "DVKH Quận 2",
  "DVKH Quận 11",
  "DVKH Quận 10",
  "DVKH Quảng Trị",
  "DVKH Quảng Ninh",
  "DVKH Quảng Nam",
  "DVKH Quảng Bình",
  "DVKH Quang Trung",
  "DVKH Phạm Văn Đồng",
  "DVKH Phạm Văn Hai",
  "DVKH Phước Tiến",
  "DVKH Phương Mai",
  "DVKH Phúc Yên",
  "DVKH Phú Xuân",
  "DVKH Phú Thọ",
  "DVKH Phú Quốc",
  "DVKH Phú Mỹ Hưng",
  "DVKH Phú Lâm",
  "DVKH Phú Hội",
  "DVKH Phan Huy Ích",
  "DVKH Nơ Trang Long",
  "DVKH Núi Thành",
  "DVKH Ninh Kiều",
  "DVKH Ninh Bình",
  "DVKH Nhà Bè",
  "DVKH Nha Trang",
  "DVKH Ngô Quyền",
  "DVKH Ngô Gia Tự",
  "DVKH Nguyễn Văn Cừ",
  "DVKH Nguyễn Trãi",
  "DVKH Nguyễn Tri Phương",
  "DVKH Nguyễn Thái Học",
  "DVKH Nguyễn Thiện Thuật",
  "DVKH Nguyễn Lương Bằng",
  "DVKH Nguyễn Hữu Huân",
  "DVKH Nguyễn Du",
  "DVKH Nghệ An",
  "DVKH Nam Định",
  "DVKH Nam Từ Liêm",
  "DVKH Nam Thăng Long",
  "DVKH Nam Sài Gòn",
  "DVKH Nam Hà Nội",
  "DVKH Mỹ Đình",
  "DVKH Móng Cái",
  "DVKH Mai Thúc Loan",
  "DVKH Lạng Sơn",
  "DVKH Lạch Tray",
  "DVKH Lạc Trung",
  "DVKH Lạc Quần",
  "DVKH Lý Tự Trọng",
  "DVKH Lý Thường Kiệt",
  "DVKH Lê Đức Thọ",
  "DVKH Lê Văn Việt",
  "DVKH Lê Văn Sỹ",
  "DVKH Lê Văn Lương",
  "DVKH Lê Trọng Tấn",
  "DVKH Lê Thanh Nghị",
  "DVKH Lê Lợi",
  "DVKH Lê Hồng Phong",
  "DVKH Lê Chân",
  "DVKH Láng Thượng",
  "DVKH Láng Hạ",
  "DVKH Lái Thiêu",
  "DVKH Lào Cai",
  "DVKH Long Thành",
  "DVKH Long Biên",
  "DVKH Long An",
  "DVKH Liễu Giai",
  "DVKH Linh Đàm",
  "DVKH Lam Sơn",
  "DVKH La Gi",
  "DVKH Kỳ Hòa",
  "DVKH Kỳ Bá",
  "DVKH Kiến An",
  "DVKH Kiên Giang",
  "DVKH Kinh Đô",
  "DVKH Kim Liên",
  "DVKH Khâm Thiên",
  "DVKH Khánh Hội",
  "DVKH Hồng Lĩnh",
  "DVKH Hồ Chí Minh",
  "DVKH Hố Nai",
  "DVKH Hải Phòng",
  "DVKH Hải Dương",
  "DVKH Hải An",
  "DVKH Hưng Yên",
  "DVKH Hưng Vượng",
  "DVKH Hóc Môn",
  "DVKH Hòa Hưng",
  "DVKH Hòa Bình",
  "DVKH Hào Nam",
  "DVKH Hàng Xanh",
  "DVKH Hàm Nghi",
  "DVKH Hà Đông",
  "DVKH Hà Tĩnh",
  "DVKH Hà Tây",
  "DVKH Hà Thành",
  "DVKH Hà Nội",
  "DVKH Hà Nam",
  "DVKH Huế",
  "DVKH Hoàng Quốc Việt",
  "DVKH Hoàng Hoa Thám",
  "DVKH Hoàn Kiếm",
  "DVKH Hiệp Hòa",
  "DVKH Hai Bà Trưng",
  "DVKH Gò Vấp",
  "DVKH Giảng Võ",
  "DVKH Gia Định",
  "DVKH Gia Lai",
  "DVKH Gang Thép",
  "DVKH Dĩ An",
  "DVKH Cửa Bắc",
  "DVKH Cộng Hòa",
  "DVKH Cẩm Phả",
  "DVKH Cầu Giấy",
  "DVKH Cần Thơ",
  "DVKH Cát Linh",
  "DVKH Cà Mau",
  "DVKH Chợ Vinh",
  "DVKH Chợ Lớn",
  "DVKH Chương Dương",
  "DVKH Châu Đốc",
  "DVKH Chánh Hưng",
  "DVKH Bố Trạch",
  "DVKH Bỉm Sơn",
  "DVKH Bến Thủy",
  "DVKH Bến Thành",
  "DVKH Bến Ngự",
  "DVKH Bến Lức",
  "DVKH Bắc Ninh",
  "DVKH Bắc Hà Nội",
  "DVKH Bắc Giang",
  "DVKH Bạch Đằng",
  "DVKH Bùi Hữu Nghĩa",
  "DVKH Bình Định",
  "DVKH Bình Thạnh",
  "DVKH Bình Thuận",
  "DVKH Bình Phước",
  "DVKH Bình Phú",
  "DVKH Bình Dương",
  "DVKH Bình Chánh",
  "DVKH Bàu Cát",
  "DVKH Bà Chiểu",
  "DVKH Ba Đồn",
  "DVKH Ba Đình",
  "DVKH An Sương",
  "DVKH An Giang",
  "Digital Factory",
  "DBS Phòng phát triển dịch vụ",
  "DA Ubank Util",
  "Cụm quỹ Trung Hòa Nhân Chính",
  "Cụm quỹ Sở giao dịch",
  "Cụm quỹ Sài Gòn",
  "Cụm quỹ Kinh Đô",
  "Cụm quỹ Hồ Chí Minh",
  "Cụm quỹ Cộng Hòa",
  "Công ty Thịnh Phát",
  "CSR Miền Nam",
  "CSR Miền Bắc",
  "CSC Trung tâm DVKH khối DN lớn",
  "CS DVKH 247 - Bộ phận chăm sóc khách hàng ưu tiên kênh tổng đài điện thoại",
  "CS DVKH 247 - Bộ phận chăm sóc khách hàng thường kênh tổng đài điện thoại",
  "CPC UW MN Phòng Thực địa và GSTD",
  "CPC UW MN Phòng thẩm định và phê duyệt tín dụng KHCN Tín chấp",
  "CPC UW MN Phòng thẩm định và phê duyệt tín dụng KHCN Thế chấp",
  "CPC UW MN Phòng thẩm định và phê duyệt tín dụng KH SME",
  "CPC UW MB Phòng Thực địa và GSTD",
  "CPC UW MB Phòng thẩm định và phê duyệt tín dụng KHCN Thế chấp",
  "CPC UW MB Phòng thẩm định và phê duyệt tín dụng KH SME",
  "CPC CA Phòng xử lý Tín dụng KH Doanh nghiệp lớn phía Bắc",
  "CPC CA Miền nam",
  "CPC CA Miền Bắc",
  "CNTT - Phòng vận hành Mạng và Viễn Thông",
  "CNTT - Phòng Quản trị dịch vụ CNTT",
  "CNTT - Phòng Công nghệ thông tin",
  "CNTT - Phòng Bảo mật CNTT",
  "CNTT - Hệ thống Way 4",
  "CNTT - Hệ thống VPBank Neo (OCB)",
  "CNTT - Hệ thống T24",
  "CNTT - Hệ thống Email",
  "CNTT - Hệ thống B2B",
  "CIB CMB - Trung tâm QHKH MN",
  "CIB CMB - Trung tâm QHKH MB",
  "CIB CMB - Phòng Kinh doanh khu vực Nam Ngân hàng giao dịch",
  "CIB CMB - Khối KHDN lớn CIB (dùng cho các khoản đặc biệt)",
  "CIB CMB - CC interface CIB miền nam",
  "CIB CMB - CC interface CIB miền bắc",
  "CIB CMB - CC interface - FITB",
  "CC247 - Ebank SD - Vận hành Ebank",
  "CC interface - KTT miền nam",
  "CC interface - KTT miền bắc",
  "Bộ phận Phân tích dữ liệu và báo cáo",
  "Bộ phận phiên dịch",
  "Bộ phận hỗ trợ nghiệp vụ",
  "Bộ phận dịch vụ KH qua đt",
  "Bộ phận ATM",
  "Bán hàng Worsite Banking MN",
  "Bán hàng Worsite Banking MB",
  "Bán hàng trực tiếp SP cho vay có TSĐB tại HN",
  "Bán hàng trực tiếp SP cho vay có TSĐB tại HCM",
  "Bán hàng trực tiếp cho vay Không TSĐB MN",
  "Bán hàng trực tiếp cho vay Không TSĐB MB",
  "Bán hàng qua điện thoại MN",
  "Bán hàng qua điện thoại MB",
  "Bán hàng PTHT Vinaphone",
  "Bán hàng PTHT Mobiphone",
  "Bán hàng PTHT FPT",
  "Bán hàng Consumer Lending MN",
  "Bán hàng Consumer Lending MB",
  "BICC - TT phân tích kinh doanh",
  "BGĐ Khối Vận Hành",
  "BGĐ Khối và trợ lý",
  "BGĐ Khối KHCN và trợ lý",
  "Bán hàng Timo",
  "DVKH Timo",
  "CPC UW MB Phòng Nhập liệu",
  "CPC UW MB Phòng thẩm định và phê duyệt tín dụng KHCN Tín chấp",
  "CPC UW MN Phòng Nhập liệu",
  "DVKH - Nhóm GDV lưu động",
  "DVKH - Phòng Dịch vụ KHDN phía Bắc và Ban giám đốc TT DV KHDN",
  "DVKH - Phòng Dịch vụ KHDN phía Nam",
  "DVKH - TT Dịch vụ khách hàng chi nhánh",
  "DVKH Bà Triệu",
  "DVKH Bách Khoa",
  "DVKH CSR Miền Bắc",
  "DVKH CSR Miền Nam",
  "DVKH Cửa Đông",
  "DVKH Đông Thọ",
  "DVKH Hải Châu",
  "DVKH An Lạc",
  "DVKH Hoàng Diệu",
  "DVKH Huỳnh Tấn Phát",
  "DVKH Hưng Lợi",
  "DVKH Kỳ Anh",
  "DVKH Lagi",
  "DVKH Lê Duẩn",
  "DVKH Lý Nam Đế",
  "DVKH Nam Thành",
  "DVKH Ngã Sáu",
  "DVKH Ngọc Lâm",
  "DVKH Nguyễn Thái Sơn",
  "DVKH Quan Hoa",
  "DVKH Quận 8",
  "DVKH Tam Hòa",
  "DVKH Tôn Đức Thắng",
  "DVKH Trung Hòa NC",
  "DVKH Vương Thừa Vũ",
  "DVKH Xuân La",
  "Priority An Dương Vương",
  "Priority Bà Triệu",
  "Priority Bách Khoa",
  "Priority Cửa Đông",
  "Priority Đông Thọ",
  "Priority Hải Châu",
  "Priority An Lạc",
  "Priority Hoàng Diệu",
  "Priority Hoàng Văn Thụ",
  "Priority Huỳnh Tấn Phát",
  "Priority Hưng Lợi",
  "Priority Kỳ Anh",
  "Priority Láng Thượng",
  "Priority Lê Duẩn",
  "Priority Lý Nam Đế",
  "Priority Nam Thành",
  "Priority Ngã Sáu",
  "Priority Ngọc Lâm",
  "Priority Nguyễn Thái Sơn",
  "Priority Quan Hoa",
  "Priority Quận 8",
  "Priority Tam Hòa",
  "Priority Tôn Đức Thắng",
  "Priority THD",
  "Priority Thống Nhất",
  "Priority VIP",
  "Priority Vương Thừa Vũ",
  "Priority Xuân La",
  "Phòng phát triển sản phẩm huy động",
  "tải khoản và thẻ",
  "SME Chợ Lớn",
  "SME Gò Vấp",
  "SME Hà Tây",
  "SME Hà Thành",
  "SME Lý Thường Kiệt",
  "SME Móng Cái",
  "SME Ngô Quyền",
  "SME Quan Hoa",
  "SME Quận 10",
  "SME Quận 2",
  "SME Quận 3",
  "SME Sở giao dịch",
  "SME Thái Hà",
  "SME Thụy Khuê",
  "SME Trần Thái Tông",
  "SME Vĩnh Long",
  "SMETrần hưng Đạo",
  "DVKH Quận 7",
  "Trung tâm dịch vụ KHƯT 89 Láng Hạ",
  "Priority TT DVKH ƯT 89 Láng Hạ",
  "SME Hà Đông",
  "DVKH Dak Lak",
  "SME Quận 11",
  "SME HUB Nam Hà Nội",
  "SME HUB Đông Hà Nội",
  "SME HUB Tây Hà Nội",
  "SME HUB Gò Vấp",
  "SME Định Công",
  "DVKH TT KD KHCN",
  "DVKH Tân Hưng",
  "SME TT KD KHCN",
  "SME An Lạc",
  "SME An Sương",
  "SME Âu Cơ",
  "SME Bà Chiểu",
  "SME Ba Đình",
  "SME Ba Đồn",
  "SME Bạch Đằng",
  "SME Bách Khoa",
  "SME Bàu Cát",
  "SME Bến Lức",
  "SME Bến Ngự",
  "SME Bến Thủy",
  "SME Bỉm Sơn",
  "SME Bình Chánh",
  "SME Bình Phú",
  "SME Bình Phước",
  "SME Bình Thạnh",
  "SME Bố Trạch",
  "SME Cẩm Phả",
  "SME Cát Linh",
  "SME Chánh Hưng",
  "SME Châu Đốc",
  "SME Chợ Vinh",
  "SME Cửa Bắc",
  "SME Cửa Đông",
  "SME Đà Lạt",
  "SME Dĩ An",
  "SME Điện Biên Phủ",
  "SME Đò Quan",
  "SME Đội Cấn",
  "SME Đội Cung",
  "SME Đông Anh",
  "SME Đông Ba",
  "SME Đống Đa",
  "SME Đông Hà",
  "SME Đông Hà Nội",
  "SME Đồng Hới",
  "SME Đông Sài Gòn",
  "SME Đồng Tâm",
  "SME Đông Thọ",
  "SME Đồng Xuân",
  "SME Gang Thép",
  "SME Giảng Võ",
  "SME Hải An",
  "SME Hai Bà Trưng",
  "SME Hàm Nghi",
  "SME Hàng Xanh",
  "SME Hào Nam",
  "SME Hiệp Hòa",
  "SME Hố Nai",
  "SME Hòa Hưng",
  "SME Hoàn Kiếm",
  "SME Hoàng Hoa Thám",
  "SME Hoàng Quốc Việt",
  "SME Hóc Môn",
  "SME Hồng Lĩnh",
  "SME Khâm Thiên",
  "SME Khánh Hội",
  "SME Kiến An",
  "SME Kim Liên",
  "SME Kỳ Bá",
  "SME Lạc Quần",
  "SME Lạc Trung",
  "SME Lạch Tray",
  "SME LaGi",
  "SME Lái Thiêu",
  "SME Lạng Sơn",
  "SME Láng Thượng",
  "SME Lào Cai",
  "SME Lê Chân",
  "SME Lê Đức Thọ",
  "SME Lê Hồng Phong",
  "SME Lê Lợi",
  "SME Lê Thanh Nghị",
  "SME Lê Trọng Tấn",
  "SME Lê Văn Lương",
  "SME Lê Văn Sỹ",
  "SME Lê Văn Việt",
  "SME Liễu Giai",
  "SME Linh Đàm",
  "SME Long Biên",
  "SME Long Thành",
  "SME Lý Tự Trọng",
  "SME Mai Thúc Loan",
  "SME Mỹ Đình",
  "SME Nam Hà Nội",
  "SME Nam Sài Gòn",
  "SME Nam Thăng Long",
  "SME Nam Thành",
  "SME Nam Từ Liêm",
  "SME Ngô Gia Tự",
  "SME Nguyễn Du",
  "SME Nguyễn Hữu Huân",
  "SME Nguyễn Lương Bằng",
  "SME Nguyễn Thái Học",
  "SME Nguyễn Thiện Thuật",
  "SME Nguyễn Trãi",
  "SME Nguyễn Tri Phương",
  "SME Nguyễn Văn Cừ",
  "SME Nhà Bè",
  "SME Ninh Kiều",
  "SME Nơ Trang Long",
  "SME Núi Thành",
  "SME Phạm Văn Đồng",
  "SME Phạm Văn Hai",
  "SME Phan Huy Ích",
  "SME Phú Hội",
  "SME Phú Quốc",
  "SME Phú Xuân",
  "SME Phúc Yên",
  "SME Phước Tiến",
  "SME Phương Mai",
  "SME Quận 8",
  "SME Quảng Nam",
  "SME Sầm Sơn",
  "SME Sơn Trà",
  "SME Sông Đà",
  "SME Tân Bình",
  "SME Tân Hưng",
  "SME Tây Hà Nội",
  "SME Tây Ninh",
  "SME Thành Công",
  "SME Thạnh Mỹ Lợi",
  "SME Thành Nam",
  "SME Thành Sen",
  "SME Thanh Xuân",
  "SME Thủ Đô",
  "SME Thường Tín",
  "SME Thủy Nguyên",
  "SME Tiên Cát",
  "SME Tôn Đức Thắng",
  "SME Trần Duy Hưng",
  "SME Trần Lãm",
  "SME Trần Nguyên Hãn",
  "SME Trần Phú",
  "SME Tràng An",
  "SME Trung Chánh",
  "SME Trung Kính",
  "SME Trung Sơn",
  "SME Trường Thi",
  "SME Từ Sơn",
  "SME Uông Bí",
  "SME Văn Phú",
  "SME Văn Thánh",
  "SME Vĩnh Yên",
  "SME Vũ Trọng Phụng",
  "SME Vương Thừa Vũ",
  "SME Vỹ Dạ",
  "SME Xuân La",
  "SME Ý Yên",
  "SME Yên Hòa",
  "SME Yên Phong",
  "Priority Tân Hưng",
  "Priority TT KD KHCN",
  "RB TT KD KHCN",
  "RB An Lạc",
  "RB Bách Khoa",
  "RB Cửa Đông",
  "RB Đắk Lắk",
  "RB Đông Thọ",
  "247",
  "Private Hub_MB",
  "Private Hub_MN",
  "Phòng Hỗ trợ Tín dụng lưu động phía Bắc và Ban Giám đốc TT Hỗ Trợ Và Xử Lý Tín D",
  "Priority Lạng Giang",
  "DVKH Rạch Dừa",
  "RB Rạch Dừa",
  "Priority Rạch Dừa",
  "Priority Quận 11",
  "DVKH Long Khánh",
  "RB Long Khánh",
  "Priority Long Khánh",
  "KHCN – Vùng 11",
  "Khối Pháp chế - KSTT – Phòng Giám sát nội bộ",
  "DVKH Xương Giang",
  "Priority Xương Giang",
  "RB Xương Giang",
  "DVKH Bảo Lộc",
  "Priority Bảo Lộc",
  "RB Bảo Lộc",
  "DVKH Đăk Nông",
  "RB Đăk Nông",
  "Priority Đăk Nông",
  "DVKH Ứng Hòa",
  "RB Ứng Hòa",
  "Priority Ứng Hòa",
  "DVKH Tuy Phong",
  "RB Tuy Phong",
  "Priority Tuy Phong",
  "DVKH Bãi Cháy",
  "RB Bãi Cháy",
  "Priority Bãi Cháy",
  "DVKH Phạm Hùng",
  "RB Phạm Hùng",
  "DVKH Phước Hải",
  "RB Phước Hải",
  "Priority Phước Hải",
  "DVKH Nguyễn Duy Trinh",
  "RB Nguyễn Duy Trinh",
  "Priority Nguyễn Duy Trinh",
  "DVKH Trà Vinh",
  "RB Trà Vinh",
  "Priority Trà Vinh",
  "DVKH Hòa Xuân",
  "RB Hòa Xuân",
  "Priority Hòa Xuân",
  "DVKH Private miền Bắc",
  "Sale Private miền Bắc",
  "DVKH Private miền Nam",
  "Sale Private miền Nam",
  "Chi nhánh An Nhơn",
  "DVKH Trần Não",
  "Priority Trần Não",
  "RB Trần Não",
  "CN Hòa Thành",
  "DVKH Đông Thủ Đô",
  "Priority Đông Thủ Đô",
  "RB  Đông Thủ Đô",
  "RB La Gi",
  "RB Tô Hiến Thành",
  "RB Hưng Vượng",
  "RB Bắc Hà Nội",
  "RB Tây Hồ",
  "KHDN - Phòng phát triển sản phẩm B2B (FITB)",
  "KHDN - IT vận hành B2B",
  "KHDN - Phòng Tư vấn và báo cáo Thuế",
  "KHDN - Sự cố B2B",
  "KHDN - Phòng DVTK KHDN",
  "KHDN - IT vận hành DV thu - chi hộ",
  "KHDN - Phòng phát triển sản phẩm thu-chị hộ (FITB)",
  "KHDN - Phòng phát triển sản phẩm Smart OTP",
  "Priority Bến Thành",
  "RB Điện Biên",
  "TT Phát triển Hệ sinh thái & Số hóa",
  "Trung tâm Số hóa Ngân hàng",
  "Phòng phát triển sản phảm huy động",
  "tài khoản và thẻ",
  "Phòng Hỗ trợ Tín dụng lưu động phía Nam và Ban giám đốc TT Hỗ Trợ Và Xử Lý Tín D",
  "KHDN - Phòng phát triển sản phẩm KHDN (thấu chi/thẻ/tài khoản..)",
  "RB Hồng Hà",
  "RB Phước Kiển",
  "RB Thảo Điền",
  "DVKH Hoa Lư",
  "DVKH Điện Biên",
  "DVKH Văn Giang",
  "DVKH Sóc Trăng",
  "DVKH Ninh Thuận",
  "DVKH Đồng Văn",
  "DVKH Kim Tân",
  "DVKH Bạc Liêu",
  "DVKH Phổ Yên",
  "DVKH Quảng Ngãi",
  "DVKH Hồng Hà",
  "DVKH Phước Kiển",
  "DVKH Thảo Điền",
  "SME Hoa Lư",
  "SME Điện Biên",
  "SME Văn Giang",
  "SME Sóc Trăng",
  "SME Ninh Thuận",
  "SME Đồng Văn",
  "SME Kim Tân",
  "SME Bạc Liêu",
  "SME Phổ Yên",
  "SME Quảng Ngãi",
  "SME Hồng Hà",
  "SME Phước Kiển",
  "SME Thảo Điền",
  "Priority Hoa Lư",
  "Priority Điện Biên",
  "Priority Văn Giang",
  "Priority Sóc Trăng",
  "Priority Ninh Thuận",
  "Priority Đồng Văn",
  "Priority Kim Tân",
  "Priority Bạc Liêu",
  "Priority Phổ Yên",
  "Priority Quảng Ngãi",
  "Priority Hồng Hà",
  "Priority Phước Kiển",
  "Priority Thảo Điền",
  "DVKH Gia Lâm",
  "RB Gia Lâm",
  "SME Gia Lâm",
  "Priority Gia Lâm",
  "TN1- Bán hàng qua điện thoại MB",
  "TN2- Bán hàng qua điện thoại MB",
  "TN3- Bán hàng qua điện thoại MB",
  "Trung tâm bán hàng chuyên biệt thẻ tín dụng",
  "WBS - TT bán hàng trực tiếp miền Nam",
  "WBN - TT bán hàng trực tiếp miền Bắc",
  "TS3 - TT bán hàng qua điện thoại Miền Nam",
  "TS1 - TT bán hàng qua điện thoại Miền Bắc",
  "TN3 - TT bán hàng qua điện thoại Miền Bắc",
  "TN2 - TT bán hàng qua điện thoại Miền Bắc",
  "TN1 - TT bán hàng qua điện thoại Miền Bắc",
  "Hub_ND - TT bán hàng trực tiếp miền Bắc",
  "HUB_HP - TT bán hàng trực tiếp miền Bắc",
  "HUB_DN - TT bán hàng trực tiếp miền Bắc",
  "DSA_CC3 - TT Bán hàng chuyên biệt thẻ tín dụng",
  "DSA_CC2 - TT Bán hàng chuyên biệt thẻ tín dụng",
  "DSA_CC1 - TT Bán hàng chuyên biệt thẻ tín dụng",
  "DS3 - TT bán hàng trực tiếp miền Nam",
  "DS2 - TT bán hàng trực tiếp miền Nam",
  "DS1 - TT bán hàng trực tiếp miền Nam",
  "DN3 - TT bán hàng trực tiếp miền Bắc",
  "DN2 - TT bán hàng trực tiếp miền Bắc",
  "DN1 - TT bán hàng trực tiếp miền Bắc",
  "CL - TT bán hàng trực tiếp miền Bắc",
  "DVKH Nguyễn Văn Huyên",
  "SME Nguyễn Văn Huyên",
  "Priority Nguyễn Văn Huyên",
  "RB Nguyễn Văn Huyên",
  "DVKH Thạch Thất",
  "SME Thạch Thất",
  "Priority Thạch Thất",
  "RB Thạch Thất",
  "DVKH Sóc Sơn",
  "SME Sóc Sơn",
  "Priority  Sóc Sơn",
  "RB Sóc Sơn",
  "DVKH Quế Võ",
  "SME Quế Võ",
  "Priority Quế Võ",
  "RB Quế Võ",
  "DVKH Đông Hương",
  "SME Đông Hương",
  "Phòng Tài khoản thanh toán & trả lương : Phụ trách về sản phẩm tài khoản thanh t",
  "Hub loan Hải Phòng",
  "RB Lạc Quần",
  "RB Lạc Trung",
  "RB Lạch Tray",
  "RB LaGi",
  "RB Lái Thiêu",
  "RB Lạng Sơn",
  "RB Láng Thượng",
  "RB Lê Chân",
  "RB Lê Đức Thọ",
  "RB Lê Lợi",
  "RB Lê Thanh Nghị",
  "RB Lê Trọng Tấn",
  "RB Lê Văn Lương",
  "RB Lê Văn Sỹ",
  "RB Lê Văn Việt",
  "RB Liễu Giai",
  "RB Linh Đàm",
  "RB Long An",
  "RB Long Biên",
  "RB Lý Thường Kiệt",
  "RB Lý Tự Trọng",
  "RB Mai Thúc Loan",
  "RB Móng Cái",
  "RB Mỹ Đình",
  "RB Nam Định",
  "RB Nam Hà Nội",
  "RB Nam Sài Gòn",
  "RB Nam Thăng Long",
  "RB Nam Thành",
  "RB Nam Từ Liêm",
  "RB Lê Hồng Phong",
  "RB Nghệ An",
  "RB Ngô Gia Tự",
  "RB Ngô Quyền",
  "RB Nguyễn Du",
  "RB Nguyễn Hữu Huân",
  "RB Nguyễn Lương Bằng",
  "RB Nguyễn Thái Học",
  "RB Nguyễn Thiện Thuật",
  "RB Nguyễn Trãi",
  "RB Nguyễn Tri Phương",
  "RB Nguyễn Văn Cừ",
  "RB Nha Trang",
  "RB Ninh Bình",
  "RB Ninh Kiều",
  "RB Nơ Trang Long",
  "RB Núi Thành",
  "RB Phạm Văn Đồng",
  "RB Phạm Văn Hai",
  "RB Phan Huy Ích",
  "RB Phú Hội",
  "RB Phú Lâm",
  "RB Phú Mỹ Hưng",
  "RB Phú Quốc",
  "RB Phú Thọ",
  "RB Phú Xuân",
  "RB Phúc Yên",
  "RB Phước Tiến",
  "RB Phương Mai",
  "RB Quận 10",
  "RB Quận 11",
  "RB Quận 2",
  "RB Quận 3",
  "RB Quận 8",
  "RB Quảng Bình",
  "RB Quảng Nam",
  "RB Quảng Ninh",
  "RB Quảng Trị",
  "RB Quang Trung",
  "RB Sài Gòn",
  "RB Sầm Sơn",
  "RB Sở giao dịch",
  "RB Sơn Trà",
  "RB Sông Đà",
  "RB Long Thành",
  "RB Tân Bình",
  "RB Tân Hưng",
  "RB Tân Phú",
  "RB Tây Hà Nội",
  "RB Thái Bình",
  "RB Thái Hà",
  "RB Thái Nguyên",
  "RB Thăng Long",
  "RB Thành Công",
  "RB Thành Đô",
  "RB Thanh Hóa",
  "RB Thạnh Mỹ Lợi",
  "RB Thành Nam",
  "RB Thành Sen",
  "RB Thanh Xuân",
  "RB Thủ Đô",
  "RB Thủ Đức",
  "RB Thụy Khuê",
  "RB Thủy Nguyên",
  "RB Tiên Cát",
  "RB Tiền Giang",
  "RB Tôn Đức Thắng",
  "RB Trần Duy Hưng",
  "RB Trần Hưng Đạo",
  "RB Trần Lãm",
  "RB Trần Nguyên Hãn",
  "RB Trần Phú",
  "RB Trần Thái Tông",
  "RB Tràng An",
  "RB Trung Hòa Nhân Chính",
  "RB Trung Kính",
  "RB Trung Sơn",
  "RB Trường Thi",
  "RB Từ Sơn",
  "RB Uông Bí",
  "RB Văn Quán",
  "RB Văn Thánh",
  "RB Vĩnh Long",
  "RB Vĩnh Phúc",
  "RB Vĩnh Yên",
  "RB Vũ Trọng Phụng",
  "RB Vũng Tàu",
  "RB Vương Thừa Vũ",
  "RB Vỹ Dạ",
  "RB Xuân La",
  "RB Ý Yên",
  "RB Yên Hòa",
  "RB Tây Ninh",
  "RB Lào Cai",
  "RB Hóc Môn",
  "RB Dĩ An",
  "RB Yên Phong",
  "RB Thường Tín",
  "RB Nhà Bè",
  "RB Trung Chánh",
  "RB Bình Chánh",
  "RB Láng Hạ",
  "RB Văn Phú",
  "DVKH Thành Đô",
  "SME Sa Đéc",
  "SME Bến Tre",
  "SME Hội An",
  "SME Bà Rịa",
  "SME Tây Sài Gòn",
  "SME Tây Sơn",
  "RB Sa Đéc",
  "RB Bến Tre",
  "RB Hội An",
  "RB Bà Rịa",
  "RB Tây Sài Gòn",
  "RB Tây Sơn",
  "Priority Sa Đéc",
  "Priority Bến Tre",
  "Priority Hội An",
  "Priority Bà Rịa",
  "Priority Tây Sài Gòn",
  "Priority Tây Sơn",
  "DVKH Sa Đéc",
  "DVKH Bến Tre",
  "DVKH Hội An",
  "DVKH Bà Rịa",
  "DVKH Tây Sài Gòn",
  "DVKH Tây Sơn",
  "DVKH Sơn Tây",
  "Kiểm soát RRVH",
  "Priority Sơn Tây",
  "Quản lý đối tác thuê ngoài",
  "RB Sơn Tây",
  "Phòng tư vấn và báo cáo Thuế",
  "SME Sơn Tây",
  "Prosland",
  "DVKH Phú Yên",
  "DVKH Phan Văn Trị",
  "DVKH Phùng",
  "DVKH Lương Thế Vinh",
  "RB Phan Văn Trị",
  "RB Phú Yên",
  "RB Phùng",
  "RB Lương Thế Vinh",
  "SME Phú Yên",
  "SME Phan Văn Trị",
  "SME Phùng",
  "SME Lương Thế Vinh",
  "Priority Phú Yên",
  "Priority Phan Văn Trị",
  "Priority Phùng",
  "Priority Lương Thế Vinh",
  "Piority Bến Thành",
  "Doi tac VNPay",
  "Doi tac Napas",
  "DVKH Lương Sơn",
  "RB Lương Sơn",
  "SME Lương Sơn",
  "Priority Lương Sơn",
  "RB Hoa Lư",
  "RB Văn Giang",
  "RB Sóc Trăng",
  "RB Ninh Thuận",
  "RB Đồng Văn",
  "RB Kim Tân",
  "RB Bạc Liêu",
  "RB Phổ Yên",
  "RB Quảng Ngãi",
  "Priority Đông Hương",
  "RB Đông Hương",
  "DVKH Diễn Châu",
  "SME Diễn Châu",
  "Priority Diễn Châu",
  "RB Diễn Châu",
  "DVKH Tân Uyên",
  "SME Tân Uyên",
  "Priority Tân Uyên",
  "RB Tân Uyên",
  "DVKH Bình Hưng",
  "SME Bình Hưng",
  "Priority Bình Hưng",
  "RB Bình Hưng",
  "DVKH Long Hải",
  "SME Long Hải",
  "Priority Long Hải",
  "RB Long Hải",
  "DVKH Đức Trọng",
  "SME Đức Trọng",
  "Priority Đức Trọng",
  "RB Đức Trọng",
  "DVKH THANH TRÌ",
  "SME THANH TRÌ",
  "RB THANH TRÌ",
  "DVKH HẢI VÂN",
  "SME HẢI VÂN",
  "Priority HẢI VÂN",
  "RB HẢI VÂN",
  "Priority Kim Mã",
  "Priority Thanh Oai",
  "Priority Như Quỳnh",
  "Priority Hùng Vương",
  "Priority Yên Lạc",
  "Priority Yên Khánh",
  "Priority Thanh Hoá",
  "Priority Hoà Hưng",
  "Priority Củ Chi",
  "Priority Đức Hoà",
  "Priority ĐẮK LẮK",
  "RB Kim Mã",
  "RB Thanh Oai",
  "RB Như Quỳnh",
  "RB Hùng Vương",
  "RB Yên Lạc",
  "RB Yên Khánh",
  "RB Thanh Hoá",
  "RB Hoà Hưng",
  "RB Đức Hoà",
  "SME Kim Mã",
  "SME Thanh Oai",
  "SME Như Quỳnh",
  "SME Hùng Vương",
  "SME Yên Lạc",
  "SME Yên Khánh",
  "SME Thanh Hoá",
  "SME Hoà Hưng",
  "SME Đức Hoà",
  "SME ĐẮK LẮK",
  "DVKH Kim Mã",
  "DVKH Thanh Oai",
  "DVKH Như Quỳnh",
  "DVKH Hùng Vương",
  "DVKH Yên Lạc",
  "DVKH Yên Khánh",
  "DVKH Thanh Hoá",
  "DVKH Hoà Hưng",
  "DVKH Đức Hoà",
  "DVKH ĐẮK LẮK",
  "Phòng phát triển Hệ sinh thái",
  "DVKH Ung Hoa",
  "RB Ung Hoa",
  "Priority Ung Hoa",
  "KHCN – Vùng 1B",
  "DVKH Sở Giao Dịch 2",
  "RB Sở Giao Dịch 2",
  "Priority Sở Giao Dịch 2",
  "DVKH Sông Cầu",
  "RB Sông Cầu",
  "Priority Sông Cầu",
  "Nhà mạng viễn thông",
  "Đối tác LynkID",
  "DVKH Lý Nhân",
  "RB Lý Nhân",
  "Priority Lý Nhân",
  "DVKH Sông Công",
  "RB Sông Công",
  "Priority Sông Công",
  "DVKH Mỹ Đức",
  "RB Mỹ Đức",
  "Priority Mỹ Đức",
  "DVKH Sơn La",
  "RB Sơn La",
  "Priority Sơn La",
  "DVKH Lạng Giang",
  "RB Lạng Giang",
  "Sản phẩm/Dịch vụ",
  "Phong QL Phan khuc AF",
  "Chi nhánh QL",
  "CPC UW MN Phòng thẩm định và phê duyệt tín dụng tiểu thương",
  "DVKH Bà Điểm",
  "DVKH Bắc Bình (Tuy Phong)",
  "DVKH Cai Lậy",
  "DVKH Cần Giờ",
  "DVKH Củ Chi",
  "DVKH Hòa Thành",
  "DVKH Tân Túc",
  "DVKH Đắk Nông",
  "DVKH Đức Hòa",
  "Priority Bà Điểm",
  "Priority Bắc Bình (Tuy Phong)",
  "Priority Cai Lậy",
  "Priority Cần Giờ",
  "Priority Hòa Thành",
  "Priority Tân Túc",
  "Priority Đắk Nông",
  "Priority Đức Hòa",
  "RB Bà Điểm",
  "RB Bắc Bình (Tuy Phong)",
  "RB Cai Lậy",
  "RB Cần Giờ",
  "RB Củ Chi",
  "RB Hòa Thành",
  "RB Tân Túc",
  "RB Đắk Nông",
  "RB Đức Hòa",
  "SME Bà Điểm",
  "SME Bãi Cháy",
  "SME Bảo Lộc",
  "SME Bắc Bình (Tuy Phong)",
  "SME Cai Lậy",
  "SME Cần Giờ",
  "SME Củ Chi",
  "SME Hòa Thành",
  "SME Long Khánh",
  "SME Lý Nhân",
  "SME Mỹ Đức",
  "SME Rạch Dừa",
  "SME Sông Công",
  "SME Sông Cầu",
  "SME Sơn La",
  "SME Trà Vinh",
  "SME Tân Túc",
  "SME Xương Giang",
  "SME Đắk Nông",
  "SME Đức Hòa",
  "SME Ứng Hòa",
  "CN hoặc đơn vị KH phản ánh",
  "Chưa xác định (hệ thống VPBank/ Ngân hàng liên minh)",
  "DVKH An Nhơn",
  "DVKH Chí Linh",
  "DVKH Chương Mỹ",
  "DVKH Hoài Đức",
  "DVKH Phước Kiểng",
  "DVKH chi nhánh",
  "Khách hàng",
  "Lỗi đối tác và hệ thống ( CNTT)",
  "Ngân hàng liên minh",
  "Nhân viên đơn vị mở thẻ",
  "Nhân viên",
  "Phòng KSRRVH",
  "Phòng PTSP huy động",
  "tài khoản thẻ",
  "Phòng phát triển sản phẩm  - Tín dụng tín chấp",
  "Priority An Nhơn",
  "Priority Chí Linh",
  "Priority Chương Mỹ",
  "Priority Hoài Đức",
  "Priority Phước Kiểng",
  "Priority Sóc Sơn",
  "Priority Thanh Trì",
  "Quy trình chính sách - P PTSP huy động",
  "RB An Nhơn",
  "RB Chí Linh",
  "RB Chương Mỹ",
  "RB Hoài Đức",
  "RB Phước Kiểng",
  "Rủi ro khách quan",
  "SME An Nhơn",
  "SME Chí Linh",
  "SME Chương Mỹ",
  "SME Hoài Đức",
  "SME Phước Kiểng",
  "Sản phẩm/quy trình",
  "TT Dịch vụ CNTT KH Doanh nghiệp",
  "TT sản phẩm Tín chấp và phân khúc Mass",
  "Đơn vị chấp nhận thẻ",
  "Đơn vị kinh doanh",
  "Đơn vị ngoài Ngân hàng",
  "Đối tác chuyển phát thẻ",
  "Đối tác",
  "DVKH",
  "Phòng thu hồi nợ",
  "Phong QL Phan khuc Private",
  "CNTT",
  "Lỗi hệ thống - CNTT",
  "Hạn chế của hệ thống - CNTT",
  "Khối CNTT",
  "CS DVKH 247 - Bộ phận chăm sóc khách hàng kênh tổng đài điện thoại"
];
